package com.peike.theatersubtitle.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.peike.theatersubtitle.db.Movie;
import com.peike.theatersubtitle.db.Subtitle;
import com.peike.theatersubtitle.db.MovieSearchResult;

import com.peike.theatersubtitle.db.MovieDao;
import com.peike.theatersubtitle.db.SubtitleDao;
import com.peike.theatersubtitle.db.MovieSearchResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieDaoConfig;
    private final DaoConfig subtitleDaoConfig;
    private final DaoConfig movieSearchResultDaoConfig;

    private final MovieDao movieDao;
    private final SubtitleDao subtitleDao;
    private final MovieSearchResultDao movieSearchResultDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieDaoConfig = daoConfigMap.get(MovieDao.class).clone();
        movieDaoConfig.initIdentityScope(type);

        subtitleDaoConfig = daoConfigMap.get(SubtitleDao.class).clone();
        subtitleDaoConfig.initIdentityScope(type);

        movieSearchResultDaoConfig = daoConfigMap.get(MovieSearchResultDao.class).clone();
        movieSearchResultDaoConfig.initIdentityScope(type);

        movieDao = new MovieDao(movieDaoConfig, this);
        subtitleDao = new SubtitleDao(subtitleDaoConfig, this);
        movieSearchResultDao = new MovieSearchResultDao(movieSearchResultDaoConfig, this);

        registerDao(Movie.class, movieDao);
        registerDao(Subtitle.class, subtitleDao);
        registerDao(MovieSearchResult.class, movieSearchResultDao);
    }
    
    public void clear() {
        movieDaoConfig.getIdentityScope().clear();
        subtitleDaoConfig.getIdentityScope().clear();
        movieSearchResultDaoConfig.getIdentityScope().clear();
    }

    public MovieDao getMovieDao() {
        return movieDao;
    }

    public SubtitleDao getSubtitleDao() {
        return subtitleDao;
    }

    public MovieSearchResultDao getMovieSearchResultDao() {
        return movieSearchResultDao;
    }

}
