package com.peike.theatersubtitle.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUBTITLE".
 */
public class Subtitle {

    private Long id;
    private String imdbId;
    private String fileName;
    private String language;
    private String duration;
    private String iso639;
    private String addDate;
    private Integer fileSize;
    private Integer downloadCount;
    private Integer fileId;

    public Subtitle() {
    }

    public Subtitle(Long id) {
        this.id = id;
    }

    public Subtitle(Long id, String imdbId, String fileName, String language, String duration, String iso639, String addDate, Integer fileSize, Integer downloadCount, Integer fileId) {
        this.id = id;
        this.imdbId = imdbId;
        this.fileName = fileName;
        this.language = language;
        this.duration = duration;
        this.iso639 = iso639;
        this.addDate = addDate;
        this.fileSize = fileSize;
        this.downloadCount = downloadCount;
        this.fileId = fileId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImdbId() {
        return imdbId;
    }

    public void setImdbId(String imdbId) {
        this.imdbId = imdbId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getIso639() {
        return iso639;
    }

    public void setIso639(String iso639) {
        this.iso639 = iso639;
    }

    public String getAddDate() {
        return addDate;
    }

    public void setAddDate(String addDate) {
        this.addDate = addDate;
    }

    public Integer getFileSize() {
        return fileSize;
    }

    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    public Integer getDownloadCount() {
        return downloadCount;
    }

    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }

    public Integer getFileId() {
        return fileId;
    }

    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

}
